/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.st.csv.reader;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void AppTestMethod() {
        App classUnderTest = new App();
        String[] args = {};
        classUnderTest.main(args);
    }
}
