/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.st.csv.reader;

import com.st.csv.reader.util.CsvBuilder;
import com.st.csv.reader.util.CsvReader;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

public class App {


    public static void main(String[] args) {
        CsvBuilder builder = new CsvBuilder();
        builder.csvBuilder();

    }
}
